export interface SeedDataset {
  organization: any;
  campuses: any[];
  buildings: any[];
  floors: any[];
  rooms: any[];
  waypoints: any[];
  routeEdges: any[];
  assets: any[];
  timetables: any[];
  tickets: any[];
  users: any[];
}

export const SEED_DATA: SeedDataset = {
  organization: {
    id: 'org-nit-001',
    name: 'National Institute of Technology',
    slug: 'nit',
    planTier: 'ENTERPRISE',
  },
  campuses: [
    {
      id: 'c-main-001',
      organizationId: 'org-nit-001',
      name: 'Main Technology Campus',
      code: 'MAIN',
      latitude: 12.9716,
      longitude: 77.5946,
    },
  ],
  buildings: [
    {
      id: 'b-cse-001',
      campusId: 'c-main-001',
      name: 'Computer Science & AI Block B',
      code: 'BLOCK_B',
      totalFloors: 3,
    },
    {
      id: 'b-admin-002',
      campusId: 'c-main-001',
      name: 'Central Administration & Library',
      code: 'BLOCK_A',
      totalFloors: 2,
    },
  ],
  floors: [
    {
      id: 'fl-b-01',
      buildingId: 'b-cse-001',
      floorNumber: 1,
      name: 'Ground Floor',
      elevationMeters: 0,
    },
    {
      id: 'fl-b-02',
      buildingId: 'b-cse-001',
      floorNumber: 2,
      name: 'Second Floor',
      elevationMeters: 4.5,
    },
    {
      id: 'fl-a-01',
      buildingId: 'b-admin-002',
      floorNumber: 1,
      name: 'Ground Floor',
      elevationMeters: 0,
    },
  ],
  rooms: [
    {
      id: 'GF-COR-01',
      floorId: 'fl-b-01',
      roomNumber: 'COR-00',
      name: 'Central Corridor',
      roomType: 'CIRCULATION',
      capacity: 120,
      isAccessible: true,
      department: 'Campus Circulation',
      latitude: 12.9715,
      longitude: 77.5945,
    },
    {
      id: 'GF-ENT-01',
      floorId: 'fl-b-01',
      roomNumber: 'ENT-00',
      name: 'Main Entrance',
      roomType: 'CIRCULATION',
      capacity: 60,
      isAccessible: true,
      department: 'Main Entry Security',
      latitude: 12.9714,
      longitude: 77.5945,
    },
    {
      id: 'GF-COE-01',
      floorId: 'fl-b-01',
      roomNumber: 'COE-01',
      name: 'COE Hall',
      roomType: 'SEMINAR_HALL',
      capacity: 80,
      isAccessible: true,
      department: 'Centre of Excellence',
      latitude: 12.9715,
      longitude: 77.5943,
    },
    {
      id: 'GF-LAD-01',
      floorId: 'fl-b-01',
      roomNumber: 'LAD-01',
      name: 'Ladies Toilet',
      roomType: 'RESTROOM',
      capacity: 15,
      isAccessible: true,
      department: 'Public Amenities',
      latitude: 12.9717,
      longitude: 77.5944,
    },
    {
      id: 'GF-SEM-01',
      floorId: 'fl-b-01',
      roomNumber: 'SEM-01',
      name: 'Main Block Seminar Hall',
      roomType: 'SEMINAR_HALL',
      capacity: 150,
      isAccessible: true,
      department: 'Main Block Academic Affairs',
      latitude: 12.9717,
      longitude: 77.5947,
    },
    {
      id: 'GF-GEN-01',
      floorId: 'fl-b-01',
      roomNumber: 'GEN-01',
      name: 'Gents Toilet',
      roomType: 'RESTROOM',
      capacity: 15,
      isAccessible: true,
      department: 'Public Amenities',
      latitude: 12.9716,
      longitude: 77.5947,
    },
    {
      id: 'GF-CCTV-01',
      floorId: 'fl-b-01',
      roomNumber: 'CCTV-01',
      name: 'CCTV Monitoring Room',
      roomType: 'MONITORING',
      capacity: 25,
      isAccessible: true,
      department: 'Campus Safety & Operations',
      latitude: 12.9715,
      longitude: 77.5947,
    },
    {
      id: 'GF-STR-01',
      floorId: 'fl-b-01',
      roomNumber: 'STR-UP',
      name: 'Upstairs',
      roomType: 'STAIRS',
      capacity: 30,
      isAccessible: false,
      department: 'Vertical Circulation',
      latitude: 12.9714,
      longitude: 77.5948,
    },
    {
      id: 'r-101',
      floorId: 'fl-b-01',
      roomNumber: '101',
      name: 'Lecture Hall 101',
      roomType: 'CLASSROOM',
      capacity: 60,
      isAccessible: true,
      department: 'Computer Science',
      latitude: 12.9716,
      longitude: 77.5946,
    },
    {
      id: 'r-102',
      floorId: 'fl-b-01',
      roomNumber: '102',
      name: 'Computing Systems Lab 102',
      roomType: 'COMPUTER_LAB',
      capacity: 40,
      isAccessible: true,
      department: 'Computer Science',
      latitude: 12.9717,
      longitude: 77.5946,
    },
    {
      id: 'r-201',
      floorId: 'fl-b-02',
      roomNumber: '201',
      name: 'Seminar Hall 201',
      roomType: 'CLASSROOM',
      capacity: 90,
      isAccessible: true,
      department: 'Computer Science',
      latitude: 12.9718,
      longitude: 77.5947,
    },
    {
      id: 'r-202',
      floorId: 'fl-b-02',
      roomNumber: '202',
      name: 'Faculty Room 202',
      roomType: 'FACULTY_OFFICE',
      capacity: 15,
      isAccessible: true,
      department: 'Computer Science',
      latitude: 12.9719,
      longitude: 77.5947,
    },
    {
      id: 'r-204',
      floorId: 'fl-b-02',
      roomNumber: '204',
      name: 'AI & Robotics Lab 204',
      roomType: 'RESEARCH_LAB',
      capacity: 40,
      isAccessible: true,
      department: 'Artificial Intelligence',
      latitude: 12.9720,
      longitude: 77.5947,
    },
  ],
  waypoints: [
    {
      id: 'wp-101',
      floorId: 'fl-b-01',
      coordinate: { latitude: 12.9716, longitude: 77.5946 },
      waypointType: 'DOOR',
      isAccessible: true,
      connectedRoomId: 'r-101',
    },
    {
      id: 'wp-102',
      floorId: 'fl-b-01',
      coordinate: { latitude: 12.9717, longitude: 77.5946 },
      waypointType: 'DOOR',
      isAccessible: true,
      connectedRoomId: 'r-102',
    },
    {
      id: 'wp-junc-1',
      floorId: 'fl-b-01',
      coordinate: { latitude: 12.97165, longitude: 77.59465 },
      waypointType: 'CORRIDOR_JUNCTION',
      isAccessible: true,
    },
    {
      id: 'wp-stair-1',
      floorId: 'fl-b-01',
      coordinate: { latitude: 12.9718, longitude: 77.5946 },
      waypointType: 'STAIR',
      isAccessible: false,
    },
    {
      id: 'wp-elev-1',
      floorId: 'fl-b-01',
      coordinate: { latitude: 12.9717, longitude: 77.5947 },
      waypointType: 'ELEVATOR',
      isAccessible: true,
    },
    {
      id: 'wp-stair-2',
      floorId: 'fl-b-02',
      coordinate: { latitude: 12.9718, longitude: 77.5946 },
      waypointType: 'STAIR',
      isAccessible: false,
    },
    {
      id: 'wp-elev-2',
      floorId: 'fl-b-02',
      coordinate: { latitude: 12.9717, longitude: 77.5947 },
      waypointType: 'ELEVATOR',
      isAccessible: true,
    },
    {
      id: 'wp-junc-2',
      floorId: 'fl-b-02',
      coordinate: { latitude: 12.9719, longitude: 77.5947 },
      waypointType: 'CORRIDOR_JUNCTION',
      isAccessible: true,
    },
    {
      id: 'wp-201',
      floorId: 'fl-b-02',
      coordinate: { latitude: 12.9718, longitude: 77.5947 },
      waypointType: 'DOOR',
      isAccessible: true,
      connectedRoomId: 'r-201',
    },
    {
      id: 'wp-204',
      floorId: 'fl-b-02',
      coordinate: { latitude: 12.9720, longitude: 77.5947 },
      waypointType: 'DOOR',
      isAccessible: true,
      connectedRoomId: 'r-204',
    },
  ],
  routeEdges: [
    { sourceWaypointId: 'wp-101', targetWaypointId: 'wp-junc-1', distanceMeters: 8, isAccessible: true, isStair: false, isElevator: false },
    { sourceWaypointId: 'wp-junc-1', targetWaypointId: 'wp-101', distanceMeters: 8, isAccessible: true, isStair: false, isElevator: false },
    { sourceWaypointId: 'wp-102', targetWaypointId: 'wp-junc-1', distanceMeters: 6, isAccessible: true, isStair: false, isElevator: false },
    { sourceWaypointId: 'wp-junc-1', targetWaypointId: 'wp-102', distanceMeters: 6, isAccessible: true, isStair: false, isElevator: false },
    { sourceWaypointId: 'wp-junc-1', targetWaypointId: 'wp-stair-1', distanceMeters: 12, isAccessible: false, isStair: true, isElevator: false },
    { sourceWaypointId: 'wp-stair-1', targetWaypointId: 'wp-junc-1', distanceMeters: 12, isAccessible: false, isStair: true, isElevator: false },
    { sourceWaypointId: 'wp-junc-1', targetWaypointId: 'wp-elev-1', distanceMeters: 15, isAccessible: true, isStair: false, isElevator: true },
    { sourceWaypointId: 'wp-elev-1', targetWaypointId: 'wp-junc-1', distanceMeters: 15, isAccessible: true, isStair: false, isElevator: true },
    { sourceWaypointId: 'wp-stair-1', targetWaypointId: 'wp-stair-2', distanceMeters: 10, isAccessible: false, isStair: true, isElevator: false },
    { sourceWaypointId: 'wp-stair-2', targetWaypointId: 'wp-stair-1', distanceMeters: 10, isAccessible: false, isStair: true, isElevator: false },
    { sourceWaypointId: 'wp-elev-1', targetWaypointId: 'wp-elev-2', distanceMeters: 10, isAccessible: true, isStair: false, isElevator: true },
    { sourceWaypointId: 'wp-elev-2', targetWaypointId: 'wp-elev-1', distanceMeters: 10, isAccessible: true, isStair: false, isElevator: true },
    { sourceWaypointId: 'wp-stair-2', targetWaypointId: 'wp-junc-2', distanceMeters: 10, isAccessible: false, isStair: true, isElevator: false },
    { sourceWaypointId: 'wp-junc-2', targetWaypointId: 'wp-stair-2', distanceMeters: 10, isAccessible: false, isStair: true, isElevator: false },
    { sourceWaypointId: 'wp-elev-2', targetWaypointId: 'wp-junc-2', distanceMeters: 8, isAccessible: true, isStair: false, isElevator: false },
    { sourceWaypointId: 'wp-junc-2', targetWaypointId: 'wp-elev-2', distanceMeters: 8, isAccessible: true, isStair: false, isElevator: false },
    { sourceWaypointId: 'wp-junc-2', targetWaypointId: 'wp-201', distanceMeters: 6, isAccessible: true, isStair: false, isElevator: false },
    { sourceWaypointId: 'wp-201', targetWaypointId: 'wp-junc-2', distanceMeters: 6, isAccessible: true, isStair: false, isElevator: false },
    { sourceWaypointId: 'wp-junc-2', targetWaypointId: 'wp-204', distanceMeters: 14, isAccessible: true, isStair: false, isElevator: false },
    { sourceWaypointId: 'wp-204', targetWaypointId: 'wp-junc-2', distanceMeters: 14, isAccessible: true, isStair: false, isElevator: false },
  ],
  assets: [
    {
      id: 'ast-p204',
      roomId: 'r-204',
      assetTag: 'P-204',
      name: 'Optoma 4K Laser Ceiling Projector',
      category: 'PROJECTOR',
      modelNumber: 'ZU720T',
      status: 'OPERATIONAL',
      specifications: { resolution: '3840x2160', lumens: 7500, mount: 'Ceiling' },
      lastServicedAt: '2026-08-15',
    },
    {
      id: 'ast-ws-01',
      roomId: 'r-204',
      assetTag: 'WS-204-01',
      name: 'NVIDIA RTX AI Workstation #01',
      category: 'COMPUTER',
      modelNumber: 'Dell Precision 7920',
      status: 'OPERATIONAL',
      specifications: { gpu: 'RTX 4090', ram: '64GB' },
      lastServicedAt: '2026-09-01',
    },
    {
      id: 'ast-ws-02',
      roomId: 'r-204',
      assetTag: 'WS-204-02',
      name: 'NVIDIA RTX AI Workstation #02',
      category: 'COMPUTER',
      modelNumber: 'Dell Precision 7920',
      status: 'MAINTENANCE',
      specifications: { gpu: 'RTX 4090', ram: '64GB' },
      lastServicedAt: '2026-09-10',
    },
    {
      id: 'ast-p101',
      roomId: 'r-101',
      assetTag: 'P-101',
      name: 'Epson High-Lumen Auditorium Projector',
      category: 'PROJECTOR',
      status: 'OPERATIONAL',
      specifications: { resolution: '1920x1080', lumens: 5000 },
      lastServicedAt: '2026-07-20',
    },
  ],
  timetables: [
    {
      id: 'tt-01',
      roomId: 'r-204',
      classCode: 'CS602',
      className: 'Deep Learning & Neural Architectures',
      facultyName: 'Dr. Evelyn Reed',
      dayOfWeek: 2, // Tuesday
      startTime: '10:00',
      endTime: '12:00',
    },
    {
      id: 'tt-02',
      roomId: 'r-204',
      classCode: 'CS704',
      className: 'Robotics Perception & Spatial AI',
      facultyName: 'Prof. Marcus Chen',
      dayOfWeek: 3, // Wednesday
      startTime: '14:00',
      endTime: '16:30',
    },
    {
      id: 'tt-03',
      roomId: 'r-101',
      classCode: 'CS201',
      className: 'Data Structures and Algorithms',
      facultyName: 'Dr. Sarah Jenkins',
      dayOfWeek: 1, // Monday
      startTime: '09:00',
      endTime: '10:30',
    },
  ],
  tickets: [
    {
      id: 't-1001',
      ticketNumber: 'TICK-1001',
      roomId: 'r-204',
      assetId: 'ast-ws-02',
      reportedByUserId: 'usr-student-01',
      assignedToUserId: 'usr-maint-01',
      issueSummary: 'GPU power rail failure during CUDA training run',
      status: 'IN_PROGRESS',
      priority: 'HIGH',
      createdAt: '2026-09-15T09:30:00Z',
    },
  ],
  users: [
    {
      id: 'usr-student-01',
      organizationId: 'org-nit-001',
      fullName: 'Alex Mercer',
      email: 'alex.mercer@nit.edu',
      role: 'STUDENT',
    },
    {
      id: 'usr-faculty-01',
      organizationId: 'org-nit-001',
      fullName: 'Dr. Evelyn Reed',
      email: 'evelyn.reed@nit.edu',
      role: 'FACULTY',
    },
    {
      id: 'usr-maint-01',
      organizationId: 'org-nit-001',
      fullName: 'Rajesh Kumar',
      email: 'rajesh.k@nit.edu',
      role: 'MAINTENANCE_STAFF',
    },
    {
      id: 'usr-admin-01',
      organizationId: 'org-nit-001',
      fullName: 'Campus Facilities Director',
      email: 'admin@nit.edu',
      role: 'CAMPUS_ADMIN',
    },
    {
      id: 'usr-super-01',
      organizationId: 'org-nit-001',
      fullName: 'Platform Operator',
      email: 'root@campusai.com',
      role: 'SUPER_ADMIN',
    },
  ],
};
